CREATE TABLE IF NOT EXISTS items (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  device VARCHAR(255) NOT NULL,
  status ENUM('on', 'off') NOT NULL DEFAULT 'off',
  room VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  image VARCHAR(1024) NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS migrations (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  schema_hash CHAR(32) NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_migrations_name (name)
);
